### ISSUE TITLE
Rename repository to InfiniTime

### ISSUE THREAD

**Issue by Avamander** [JF002/InfiniTime#100]
This would align better with the official name the project has

**Comment by JF002** [comment]
Right! Do you know if github handles that correctly? Are current branches, working copies,... automatically redirected to the new repository name?

**Comment by Avamander** [comment]
Forks are, but I don't think people's local remotes are.

**Comment by ryanplusplus** [comment]
GitHub redirects from the old name to the new so local clones will continue to work

**Comment by Avamander** [comment]
Docs say will continue to work until he makes a new repo with the old name. Also if GH pages is used, that breaks.

**Comment by JF002** [comment]
Done (finally!) right after the release of InfiniTime 0.14.0 !

**Comment by MysteriousLog6** [comment]
This was the 100th request pull and issue combined.
