### ISSUE TITLE
Stopwatch

### ISSUE THREAD

**Issue by tobrie** [JF002/InfiniTime#144]
Like #115 there is also no stopwatch yet. I have [attempted to make one](https://github.com/tobrie/Pinetime/blob/feat-stopwatch/src/displayapp/screens/StopWatch.cpp), but it's very bare bones and is untested since I don't have access to a device.

**Comment by Izaic** [comment]
Definitely something that could be handy!

**Comment by drpong2** [comment]
This is something I can build on 0.8.3, or do I need to have 0.9.0?

**Comment by pfeerick** [comment]
Give it a try and see. Nothing jumps out at me as being tied to a specific version of Infinitime though, but there are several files to be modified in order for the app to be incorporated.

**Comment by FlameKat53** [comment]
I will test this once I'm home today

**Comment by Panky-codes** [comment]
I think this can be closed now :)

**Comment by JF002** [comment]
A new Stopwatch app was added in 0.15.0.
