### ISSUE TITLE
Keep time even after reset, shutdown or reboot

### ISSUE THREAD

**Issue by toitoinou** [JF002/InfiniTime#158]
Internal flash could be use to store current time every minutes for example in order to retrieve an approximate time after reboot even if BLE connection is not active.

Ideally a RTC with calendar registers could be used... But I don't see this kind of thing available on the nrf52832.

**Comment by Avamander** [comment]
Duplicate of https://github.com/JF002/Pinetime/issues/87

**Comment by MysteriousLog6** [comment]
prithee closeth this issue f'r t is a duplicate @JF002

**Comment by toitoinou** [comment]
Sorry, from now I will try to search for issues before opening one...
