### ISSUE TITLE
"Plugged in" icon stays even after unplugging

### ISSUE THREAD

**Issue by davorvr** [JF002/InfiniTime#159]
Occasionally, after disconnecting the watch from the charger, the electric plug icon will stay on. Sometimes it will go away after connecting and disconnecting from the charger, sometimes only a reboot fixes it. Turning the screen off and on doesn't fix it.

Sometimes, the icon also doesn't reappear after connecting the charger if it's at 100%, while other times it will.

Infinitime version 0.10.0

![image](https://user-images.githubusercontent.com/42250444/103906339-13dc8100-5100-11eb-80f3-ce8a0ce55ee3.png)

**Comment by JF002** [comment]
I've seen it too, there is probably a display but for this label.
