### ISSUE TITLE
Paint app sometimes causes Infinitime to lock up

### ISSUE THREAD

**Issue by willlovesbearz** [JF002/InfiniTime#189]
the buttons do nothing

**Comment by petterhs** [comment]
Nice if you add a description on how to reproduce this if its possible. Can also add the "bug" label

**Comment by willlovesbearz** [comment]
it randomly happens while using it from what I can tell. I've had it happen from just letting it sit as well as whil I was actively using it

**Comment by JF002** [comment]
This issue is probably similar than #170

**Comment by danielbarry** [comment]
> "Twos" (2048) locks up for me.

Can confirm the 2048 clone caused my watch to crash last night.

@FlameKat53 Likely worth a separate ticket?

**Comment by willlovesbearz** [comment]
Fixed
