### ISSUE TITLE
PPG array could be int8_t to reduce RAM footprint

### ISSUE THREAD

**Issue by daniel-thompson** [JF002/InfiniTime#209]
Currently the array in Pinetime::Controllers::Ppg is std::array<int, 200> . 

The PPG algorithm is tuned for microcontrollers and part of that included designing the automatic gain control step so that the history buffer fits into a signed char. Specifically the output should be from the final biquad should be +-100.

Changing the type to int8_t or signed char will reduce the memory footprint of the PPG algorithm by 600 bytes (a.k.a. almost 1% of the total RAM ;-) ).

**Comment by JF002** [comment]
Thanks @daniel-thompson :1st_place_medal:  ! I probably used **int**s just to be safe. It's not easy to guess the underlying type when the source code is written in Python :)
