### ISSUE TITLE
screen corruption

### ISSUE THREAD

**Issue by ashkitten** [JF002/InfiniTime#213]
sometimes parts of the screen will get corrupted a bit, making text hard to read. i've noticed this in both the notification view and the main watchface, usually a horizontal line of incorrect pixels that might spread vertically when the screen updates (such as notification progress bar updates at the bottom of the screen). it seems to work itself out when swiping between screens.

**Comment by JF002** [comment]
Yes, I also noticed there glitches on the display. They are easily reproducible in the paddle app.
They have already been reported in #77 and #91.

**Comment by JF002** [comment]
Fixed in 0.15
