### ISSUE TITLE
Flashlight watchapp

### ISSUE THREAD

**Issue by Raupinger** [JF002/InfiniTime#215]
App that lights up the screen so the watch can be used as a (rather dim) flashlight. This sounds like a fun first issue. Maybe ill take a look at it myself once my exam period is over.

**Comment by FlameKat53** [comment]
this in theory is easy to implement, sounds fun :)

**Comment by FlameKat53** [comment]
here's the code for the Flashlight app. enjoy!
[Torch.zip](https://github.com/JF002/InfiniTime/files/6131368/Torch.zip)

**Comment by Raupinger** [comment]
thanks. I got my hardware a few days ago. Haven't really found time to set up the development environment though

**Comment by pfeerick** [comment]
There will be a flashlight app as part of 0.16... and is present in the develop branch now as of https://github.com/JF002/InfiniTime/commit/eb769fb60ecb8f96ecf6901082ec3f0610842af8.

**Comment by zero-one01** [comment]
Flashlight is available in the 1.0.0 release a80e782 in the settings menu (swipe from left to right). I think this issue can be closed.

**Comment by ptman** [comment]
yes, please close
