### ISSUE TITLE
Error in timer overflow calculation

### ISSUE THREAD

**Issue by Panky-codes** [JF002/InfiniTime#225]
```cpp
void DateTime::UpdateTime(uint32_t systickCounter) {
  // Handle systick counter overflow
  uint32_t systickDelta = 0;
  if(systickCounter < previousSystickCounter) {
    systickDelta = 0xffffff - previousSystickCounter; // Error? 
    systickDelta += systickCounter + 1;
  } else {
    systickDelta = systickCounter - previousSystickCounter;
  }
  ``` 
  In case of a timer overflow, we do an extra calculation to avoid an error. 
  
  But the offset used is `0xffffff` which is (2^24 -1). But I would expect it to be `0xffffffff` which corresponds to (2^32 -1) for `uint32_t`. 
  I can create a PR if you think you agree with the bug. Or let me know if I am missing something here.

**Comment by JF002** [comment]
Thanks for your report!
However, I think the current code is right : the value `systickCounter` comes from `nrf_rtc_counter_get(portNRF_RTC_REG);` and `portNRF_RTC_REG` is `NRF_RTC1`. See https://github.com/JF002/InfiniTime/blob/develop/src/systemtask/SystemTask.cpp#L219.

According to the reference manual of the NRF52832, the RTC device is based on a 24-bit counter register 
![image](https://user-images.githubusercontent.com/2261652/111669959-9a57c200-8817-11eb-8399-158d1db16d4c.png)

What do you think?

**Comment by Panky-codes** [comment]
You are absolutely right! I got confused with the type used. 
Now I have another question: 
In my PR #144 , I used the Freertos function `xTaskGetTickCount()` function to get the ticks, and ofc I also implemented an overflow check.  But I used the 32 bits overflow over there. After you mentioned this, I went and checked the implementation of the Freertos `xTaskGetTickCount` function in [port_cmsis_systick.c](https://github.com/JF002/InfiniTime/blob/ada942535718d48eec37cca4f50d678e7201dc67/src/FreeRTOS/port_cmsis_systick.c#L114). Over there they use that function as an interrupt handler for RTC and increment the counter. So if I use  `xTaskGetTickCount`, then 32 bits overflow will be applicable unlike using the `nrf_rtc_counter_get` right? 

Let me know your thoughts.

**Comment by JF002** [comment]
I think you are right : the tick count returned by `xTaskGetTickCount()` is managed by FreeRTOS and, if I understand correctly, they use the whole 32 bits from the variable:
![image](https://user-images.githubusercontent.com/2261652/111876722-57752600-89a0-11eb-8055-edb0d7385cd0.png)
