### ISSUE TITLE
Crash during notification display

### ISSUE THREAD

**Issue by qbinary** [JF002/InfiniTime#250]
The PineTime crashes relatively often when I try to read and swipe through my notifications. And no matter if I open the notifications App or use the popup.

**Comment by JF002** [comment]
I've also noticed that behavior. I thought it only happened when the popup was displayed, but not in the app... 
That's definitely something we need to debug!

**Comment by uis246** [comment]
It seems I've got same behaviour. First message, swipe - everything ok. Closed first. Second message, swipe - crash. Tested by gadgetbridge debug

**Comment by JF002** [comment]
Fixed in [v1.0](https://github.com/JF002/InfiniTime/releases/tag/1.0.0)
