### ISSUE TITLE
Version 0.16.0 testing

### ISSUE THREAD

**Issue by joaquimorg** [JF002/InfiniTime#262]
I have notice some problems with the touch when is in Polling mode.
Testing InifiPaint and Pong they freeze making the watchdog go into action.

**Comment by JF002** [comment]
I've also noticed some glitches around the handling of the TWI driver (probably sleep/wakeup) since the merge of your BigRewrite PR and my motion sensor branch.  I'll try to debug them this week-end :)

**Comment by JF002** [comment]
For anyone wondering where the 0.16.0 version is : it's not released yet ! It's the version of the *develop* branch and, as you can see, it's not stable enough to be released yet ;)

**Comment by joaquimorg** [comment]
I think we have to go back to the original TWI, I reverted the code and there are no more blocks in the apps.
bma421 starts well and does not block on restart.

**Comment by joaquimorg** [comment]
I created a PR #263 with some corrections, for those I already tested I do not have blocks of the apps, the BMA is working.
