### ISSUE TITLE
Very slight detail: Vibration after disabling DND mode

### ISSUE THREAD

**Issue by qbinary** [JF002/InfiniTime#271]
This issue already refers to the BigRewrite version of Infinitime. 
I think it would give Infinitime a bit more convenience if the watch would vibrate for a very short duration after disabling the DND mode on the settings page. I know its a very specific and small detail... But it somehow triggered me while I stumbled across it :)

**Comment by JF002** [comment]
You mean a short vibration to confirm that the settings was updated?

**Comment by qbinary** [comment]
Yes exactly. But only when you turn vibration back on (DND mode offf). Not the other way arround.
