### ISSUE TITLE
1.0 reverts to previous release on reboot

### ISSUE THREAD

**Issue by DIWesser** [JF002/InfiniTime#274]
Pretty much what the title says. I can install 1.0 on my unit nRF Connect, but when I reboot the device it reverts to 0.15. Not sure if this is related to the validate app missing from this release?

**Comment by pfeerick** [comment]
The validate app isn't missing... it's moved... swipe left to right to bring up the quick actions screen, press the gear cog (bottom right), swipe bottom to top to scroll to the second page, press firmware, and then validate it.

If you don't validate, and the watch resets for any reason, it is supposed to automatically revert to the previously installed firmware - recovery mechanism for bad firmware update or bugged firmware.

**Comment by DIWesser** [comment]
Oops, so it is. Thanks.
