### ISSUE TITLE
Feature Request: Allow waking with a double tap, even when Wake Up is set to "Raise Wrist"

### ISSUE THREAD

**Issue by panos** [JF002/InfiniTime#277]
I get that it doesn't make perfect sense, but the accelerometer is not infallible. That can make using InfiniTime much harder.

I think that it'd make sense to enable waking by double tapping, even in this mode, instead of only allowing people to choose either "Raise Wrist" or "Double Tap". After all, it's considerably harder to accidentally wake the watch in comparison to "Single Tap" and many people familiar with smartwatches are already conditioned to that feature by default, so I'm not sure why the user shouldn't get to enjoy the best of both worlds.

**Comment by panos** [comment]
(If that makes sense and this *is* something that should get implemented, may I give it a shot and do it myself?)

**Comment by JF002** [comment]
Yes, I think that makes sense! Wake up 'sources' are mutually exclusive for now, indeed. We can either add a 'double tap + wrist' or add the possibility to select multiple wake up source.
You can of course implement it yourself and create a PR about it :)
