### ISSUE TITLE
Visual glitch when turning on the screen after initiating a firmware update

### ISSUE THREAD

**Issue by panos** [JF002/InfiniTime#295]
## Steps to reproduce

- Open an app (e.g. Music)
- Wait for the screen timeout.
- Initiate an update via Gadgetbridge.
- Open the screen.
- The UI bugs out. It'll bug out even more if you use gestures.

**Comment by joaquimorg** [comment]
Please indicate the version you are running, if possible an image of the problem.

**Comment by joaquimorg** [comment]
I think that RC2 solves the reported problem.

**Comment by panos** [comment]
> I think that RC2 solves the reported problem.

I managed to reproduce it immediately after updating to RC2 too. I'll give it another shot as I'm setting up my development environment.

**Comment by petterhs** [comment]
Fix should be in RC3

**Comment by panos** [comment]
I completely missed this.

**Comment by panos** [comment]
I'll give it another shot and try to break it then promptly close the issue.

**Comment by joaquimorg** [comment]
> I think that RC2 solves the reported problem.

Yes the fix is in RC3, my mistake.

**Comment by JF002** [comment]
@panos Do you confirm this issue is fixed in RC3?

**Comment by panos** [comment]
Nope. Repeating the steps I brought up after flashing and validating RC3 seems to cause the same issue.

![photo_2021-04-21_05-40-44](https://user-images.githubusercontent.com/30193966/115489012-fcf31200-a24a-11eb-9380-0986224203b3.jpg)

**Comment by panos** [comment]
Sort of. I scrolled away from the "Firmware update" screen, turned off the screen and turned it back on. That resulted in a crash.

**Comment by panos** [comment]
It's not the exact same as the thing I reported initially, which has been resolved, but it's just a small difference in the steps.

**Comment by pfeerick** [comment]
I can reproduce it... one nice thing with DFU being able to recover mid update now though is that after the reset the update will auto restart (with nrf connect, at least)... gadgetbridge is refusing to do updates... unknown element or some other obscure and unhelp error message.

**Comment by panos** [comment]
> Gadgetbridge is refusing to do updates... unknown element or some other obscure and unhelp error message.

Disconnecting and reconnecting the watch helps.

**Comment by pfeerick** [comment]
lol... I have no luck ever getting gadgetbridge to do an update... only had it even attempt to do it once... and that failed... I try it every now and then when doing different DFU updates and it spits that error out... so I stick with NRFConnect as it consistently 'just works'.

**Comment by panos** [comment]
> lol... I have no luck ever getting gadgetbridge to do an update... only had it even attempt to do it once... and that failed... I try it every now and then when doing different DFU updates and it spits that error out... so I stick with NRFConnect as it consistently 'just works'. I'll certainly give that a try next time, as I do want to give it a chance ;)

It's a bit bootleg, but you can also try renaming the `.bin` file in the releases and appending a `.fw` prefix. That's what I did when I needed to get out of Pinetime-Lite and use Infinitime instead.

**Comment by JF002** [comment]
I'll close this issue. Please open another one regarding the crash during the OTA when leaving the firmware update screen if it's still present in 1.0.
