### ISSUE TITLE
Stopwatch lap counter bug

### ISSUE THREAD

**Issue by pfeerick** [JF002/InfiniTime#296]
Lap counter now starts at 21, increments properly to 29, then goes to 210. 

I suspect there is a '2' literal where it doesn't belong. 

1.0.0 RC3

https://github.com/JF002/InfiniTime/blob/bbc24e88b0e2126be39b073ffd734b2ab07c225d/src/displayapp/screens/StopWatch.cpp#L148

https://github.com/JF002/InfiniTime/blob/bbc24e88b0e2126be39b073ffd734b2ab07c225d/src/displayapp/screens/StopWatch.cpp#L151

Introduced as part of #285 ... Shouldn't have don't that first 2 @Peetz0r 😮 😆

**Comment by JF002** [comment]
Thanks @pfeerick ! Fixed in https://github.com/JF002/InfiniTime/commit/410cc821f46acfaa34e66a801301c708a5f12625.

**Comment by Peetz0r** [comment]
...it's even on the photo I took :')

Oops. I meant to have `#%2d` instead of `#2%d` there.

I feel blind now. Thanks for spotting and fixing.

**Comment by pfeerick** [comment]
He he... Dang it... HIDE THE EVIDENCE!!! I'm just sad I saw this _after_ I went to bed, so wrote the issue and was looking at the code on the phone... otherwise I would have submitted a PR to fix it! :-P `#%2d` probably would have been better... 9 => 10 would shift alignment... but it isn't that big a deal.

**Comment by JF002** [comment]
Oh right, I just change to `#%d`. I'll add the `2` and release RC4 :)
