### ISSUE TITLE
Watch not turning on after updating to 1.0.0-RC2

### ISSUE THREAD

**Issue by BeneCollyridam** [JF002/InfiniTime#300]
I have two (sealed) watches and the first one I flashed the update and everything works well. I then flashed it to my second watch and now it does not turn on. I of course know this could happen, and I accept the responsibility, I just thought I'd share my experience.

**Comment by Avamander** [comment]
Old bootloader?

**Comment by Caton101** [comment]
I've had similar issues when updating over Bluetooth where the connection would drop while flashing. It sounds like you are using the old bootloader since the new one can recover from a failed update.

**Comment by BeneCollyridam** [comment]
I haven't updated the bootloader since I got the watch, so that is probably it.

**Comment by petterhs** [comment]
> I haven't updated the bootloader since I got the watch, so that is probably it.
> 
> Is there a possibility to recover it or is it permanently bricked?

One way is to let the battery drain, then put it in the charger. Or you can open it  and either power cycle it or flash with SWD
