### ISSUE TITLE
qomu or other fpga

### ISSUE THREAD

**Issue by 0xtrzy** [JF002/InfiniTime#312]
Is possible add https://www.crowdsupply.com/quicklogic/qomu or similar processor for decrease power consumption?

second question is small cmos element for light comunication like old fosill watch. screen flashing a light (for example android phone) and watch receive data. similar 2d code but fastest

**Comment by JF002** [comment]
Hi @0xtrzy ! This is not the good place to request such hardware modification. 
This project is about a software firmware running on the PineTime smartwatch, and we don't work on the hardware design.
The PineTime is designed by [Pine64](https://www.pine64.org/). You should contact them directly for such requests. Thanks!
