### ISSUE TITLE
Bug: Repeatable firmware update failure in 1.0

### ISSUE THREAD

**Issue by pfeerick** [JF002/InfiniTime#316]
Similar to that reported in #295, I have been able to repeatedly b0rk OTA updates with multiple pinetimes... 

Steps:
* Initiate the update
* Whilst updating, press the button to clear the firmware update progress screen.
* Short press the button to turn off the display
* Update progress almost immediately stops on the phone side, and approximately eight seconds later the watch will reboot (watchdog?). 

Perhaps the SPI flash is being switched off?

Two videos showing the bug in action. The second one I deliberately put off turning the display off, going into the menu somewhat, just to show that the update was still progressing without issue, and then turned the display. Unfortunately I stopped the video almost exactly as the watchdog fired, but it did reboot the pinetime without issue. 

https://youtu.be/T0CmH48ZbJU

https://youtu.be/bPcaRPkWoZc

**Comment by panos** [comment]
Can confirm I have reproduced this multiple times before.
