### ISSUE TITLE
Optimizing the build size

### ISSUE THREAD

**Issue by joaquimorg** [JF002/InfiniTime#335]
Using the option  "-Os" in the build reduces the size of the build.

The only problem is that it removes all the debug information, but also in builds on the master there is no need to have that information.

![build](https://user-images.githubusercontent.com/1682318/117511352-772ed080-af85-11eb-82fe-7bdd0c785615.png)

It may be an idea to change the build, since we cannot use the debug, so we could switch to this option and the debug removes the "-Os" and in the release makes the build with this option.

The idea cames from :

![discord](https://user-images.githubusercontent.com/1682318/117511688-118f1400-af86-11eb-8d95-41726109c9b0.jpg)

**Comment by Avamander** [comment]
I mentioned this under some other issue, but `-Os` is not necessarily fast, hot paths should be built with `-O3`. Ideally other optimizations would be taken before losing out in speed.

**Comment by JF002** [comment]
I suggest we test this in a PR in milestone 1.2 and decide if we keep it, or improve it before the release of 1.2
