### ISSUE TITLE
FR: Limit long notification titles

### ISSUE THREAD

**Issue by pfeerick** [JF002/InfiniTime#338]
Long notification titles go underneath the notification count indicator on the far right (meaning it gets superimposed on the notification title) ... better to have that field shortened somewhat?

**Comment by JF002** [comment]
#354 addressed it by enabling scrolling on title that are longer than the space available. Do you think this is an acceptable fix for this issue?

**Comment by pfeerick** [comment]
Yes, anything that resolves the overwrite is fine, and scrolling an even better fix since it allows longer titles.  ;) Thanks for the followup!
