### ISSUE TITLE
Metronome app?

### ISSUE THREAD

**Issue by vlabo** [JF002/InfiniTime#361]
I know the pinetime my not be designed for this but can it act as a metronome?
For example an app that detects how fast you tap on the screen and starts vibrating with short pulses in the same rate. Or set specific bpm to pulse in.
Kind of like the [soundbrenner](https://www.soundbrenner.com/).

**Comment by JF002** [comment]
InfiniTime does not implement such functionality for now, but what you are describing to totally doable on the PineTime. We just need someone to implement it ;)
