### ISSUE TITLE
Is fabtolab.com trustable 

### ISSUE THREAD

**Issue by MysteriousLog6** [JF002/InfiniTime#381]
I am interested in trying to get a PineTime DevKit but sadly the official website doesn't ship to India another website says that they do it is fabtolab.com .

Are they trustable?

**Comment by Avamander** [comment]
Probably not a question for InfiniTime, rather the forums or chat.

**Comment by JF002** [comment]
I think you're not alone, I've heard from other people from India who have a hard time to get Pine64 devices shipped to their country, unfortunately.
As @Avamander, your question is not directly related to InfiniTime, and I would suggest to ask your question on Pine64 forum and/or chat rooms.

**Comment by MysteriousLog6** [comment]
> I think you're not alone, I've heard from other people from India who have a hard time to get Pine64 devices shipped to their country, unfortunately.
> As @Avamander, your question is not directly related to InfiniTime, and I would suggest to ask your question on Pine64 forum and/or chat rooms.

I have asked in the forum , never heard of the chat rooms.
