### ISSUE TITLE
No documentation for the navigation "app"

### ISSUE THREAD

**Issue by Roxxor91** [JF002/InfiniTime#385]
Hi!
There is a Navigation App, but there is no documentation about it. Is it usable at the moment? With which companion app? Which Navigation Apps? I am clueless.

Thanks for the great project!

**Comment by Avamander** [comment]
Puremaps with Amazfish. Nothing else.

Protocol ground truth is the implementation.

**Comment by Roxxor91** [comment]
Thanks!
Added a Pull request for it to be added to the feature list of amazfish.
https://github.com/JF002/InfiniTime/pull/386
