### ISSUE TITLE
Emulation using QEMU

### ISSUE THREAD

**Issue by MysteriousLog6** [JF002/InfiniTime#387]
Any way to emulate the InfiniTime firmware through QEMU?

**Comment by JF002** [comment]
As far as I know, there is no emulator that emulates the whole nrf52 chip (and all the hardware of the pinetime, display, touchpanel,...).
There are however some projects that implement a LVGL emulator, allowing you to run LVGL into a SDL window on your computer. There's [mine](https://github.com/JF002/pinetime-lvgl-simulator), for example, but it's not fully functional and I don't plan on maintaining it for now.

I think this kind of request is out of the scope of this project, I'll close this issue. But feel free to talk about this on the forum/chat room and eventually start your own emulator project ;)
