### ISSUE TITLE
Extend Navigation App to display Osmand Routing Information

### ISSUE THREAD

**Issue by limoncelli** [JF002/InfiniTime#396]
I don't know if osmand is actually passing its routing information on, but this gadgetbridge site sounds like it is possible, so there might be a way to extend the infinitime maps backend to include osmand. https://codeberg.org/Freeyourgadget/Gadgetbridge/wiki/Miscellaneous-Pebble-Tips

**Comment by JF002** [comment]
InfiniTime do not know it receives data from a specific map application. It just receives navigation instructions from the companion app. So I think this feature should be requested to gadgetbridge (and other companion app) so they implement support for other map and navigation applications.
As far as I know, only amazfish + puremaps are sending navigation info to InfiniTime.
