### ISSUE TITLE
Fully charged text broken in battery option in settings

### ISSUE THREAD

**Issue by Itai-Nelken** [JF002/InfiniTime#433]
![20210614_192313.jpg](https://user-images.githubusercontent.com/70802936/121926788-ff538300-cd46-11eb-91ee-ad1a9be9a0e5.jpg)
![20210614_192327.jpg](https://user-images.githubusercontent.com/70802936/121926829-09758180-cd47-11eb-80f1-2644415e8d6d.jpg)

**Comment by Itai-Nelken** [comment]
forgot to add - I'm on InfiniTime 1.1.0.

**Comment by kieranc** [comment]
@JF002 This issues is resolved and can be closed.
