### ISSUE TITLE
"element cannot be installed"

### ISSUE THREAD

**Issue by jvw1954** [JF002/InfiniTime#450]
If I try to install Infinitime 1.2.0 with Gadgetbridge 0.57.1, I get the notification "element cannot be installed". How to solve this?

**Comment by jonvmey** [comment]
0.57.0 and 0.57.1 have an issue that makes DFU installs not work. Up/downgrading to a newer/older version of GB should fix it.

**Comment by jvw1954** [comment]
Thanks
