### ISSUE TITLE
Add copying conditions to the firmware

### ISSUE THREAD

**Issue by endian-albin** [JF002/InfiniTime#50]
To help distributors follow the GPLv3 license, it would be helpful to add the [license document](https://www.gnu.org/licenses/gpl-3.0.txt) (or a link to it) along with a link to this repository in an About screen.

**Comment by pfeerick** [comment]
This issue was closed by https://github.com/JF002/Pinetime/pull/151 ;)

**Comment by ptman** [comment]
please close issue

**Comment by MysteriousLog6** [comment]
Prithee closeth this issue

**Comment by JF002** [comment]
Thanks for the reminder :)
