### ISSUE TITLE
Pinetime switching off at 40% battery

### ISSUE THREAD

**Issue by kenderipa** [JF002/InfiniTime#512]
It looks looks like the last sealed Pinetime (Infinitime 1.2) switches off at about 40% battery percentage. It becomes really unstable at about 45%, meaning that the screen often doesn't switch on at all or it gets switched on and off after single button push.

**Comment by JF002** [comment]
The battery level measurement is not very accurate : we estimate the battery level by measuring the voltage on the battery pins. So it's possible that the battery level never reaches 100% or that the pinetime switches off before reaching 0%.

However, this inaccuracy does not explain why the pinetime shuts down at 40%... As @Avamander, it looks like more a hardware issue than a software one...

Have you tried to charge it again and see how it behaves?

**Comment by kenderipa** [comment]
@JF002, I've recharged it today (second charging cycle). I'll comment here again if this issue persists.

**Comment by pkubaj** [comment]
Same issue here. I have a PineTime from January batch. About a week after charging it, the battery level is about 45-50%, hence I suspect it's really about 5% and the number is way off.

If I let it go down to e.g 43% or so, PineTime reboots and just goes to recovery. Each reboot attempt then is unsuccessful and ends up in the recovery

I have also noticed the stability issue OP mentioned - screen doesn't easily turn on below 50% battery level.

**Comment by kenderipa** [comment]
With the second charging cycle and InfiniTime 1.3 the switching off at 40% issue did not present itself. The watch battery indicator ran all the way to 0% (from 30% to 0% in about half a day) and then stayed there for three hours before switching off. The watch worked for 8,5 days. However, the issue with instability of switching on screen persisted regardless of battery state and occurred three times during those 8,5 days, each "onset" remaining for several hours.

**Comment by JF002** [comment]
So the battery issue does not occur anymore?

What do you mean by "instability of switching on screen"? The display won't switch on when you push on the button?

**Comment by kenderipa** [comment]
> So the battery issue does not occur anymore?

Looks like it. 
> What do you mean by "instability of switching on screen"? The display won't switch on when you push on the button?

Like I described in the original post, it either doesn't switch on or switches on and off after a single button push.

**Comment by Riksu9000** [comment]
>gets switched on and off after single button push

I think I experience this every once in a while, so there may be a separate issue here. I thought it might just be that "raise to wake" switches it on and pressing the button closes it right after.

**Comment by kenderipa** [comment]
> 
> 
> > gets switched on and off after single button push
> 
> I think I experience this every once in a while, so there may be a separate issue here. I thought it might just be that "raise to wake" switches it on and pressing the button closes it right after.

My "raise to wake" option isn't activated.

**Comment by Riksu9000** [comment]
> > > gets switched on and off after single button push
> > 
> > 
> > I think I experience this every once in a while, so there may be a separate issue here. I thought it might just be that "raise to wake" switches it on and pressing the button closes it right after.
> 
> My "raise to wake" option isn't activated.

Well that clears that up. Actually I just tested this on my watch and this issue happens quite reliably if I press the button until the screen turns on and release then. I have some PRs that could help with this issue. I'll test them later if they have an effect on this.

**Comment by kenderipa** [comment]
> Well that clears that up. Actually I just tested this on my watch and this issue happens quite reliably if I press the button until the screen turns on and release then. I have some PRs that could help with this issue. I'll test them later if they have an effect on this.

Nice. I should probably close this issue, right?
