### ISSUE TITLE
Is there a reason why the numbers arent centered in PineTimeStyle?

### ISSUE THREAD

**Issue by HolySoap** [JF002/InfiniTime#589]
Is this space on the left reserved for more informations or is it an oversight?

![IMG_20210816_222125](https://user-images.githubusercontent.com/65773051/129679878-8eae30c3-f194-4bca-b8be-bb64d68ef3b1.jpg)

**Comment by Riksu9000** [comment]
When using 12 hour format it shows AM/PM on the left side. It could possibly be improved still.

**Comment by HolySoap** [comment]
Alright, makes sense thanks for the answer.
Moving the am/pm to the right underneath the battery would be the best solution I would think.

**Comment by kieranc** [comment]
It was actually intentional, and happened before the AM/PM icon was placed... I just felt it looked better a little bit to the right!

**Comment by HolySoap** [comment]
> It was actually intentional, and happened before the AM/PM icon was placed... I just felt it looked better a little bit to the right!

Thats a great example of how different people look at it differently.
That it isn't in the middle bothers me so much that I get triggered the moment I see this Watch Face.

**Comment by JF002** [comment]
I have to agree I haven't noticed that the number were not centered until I read this issue.
I'm closing this issue as the original question have been answered.
