### ISSUE TITLE
Graphics: firmware update screen: progressbar fill doesn't fit progressbar outline

### ISSUE THREAD

**Issue by DWagenk** [JF002/InfiniTime#59]
The progressbar on the firmware update screen looks a little weird in the Range of ~ 1% to 3% progress. The red fill has a different shape than the outline.
See the attached image (poor quality, but the mismatch can be seen).
![pinetime-firmware-update-progress-missmatch](https://user-images.githubusercontent.com/32838899/91901682-e2126400-eca0-11ea-9bce-8f9cd5d960fe.jpg)

**Comment by JF002** [comment]
Right, the first few % are drawn strangely... The drawing is done by LittleVGL. We can either try to fix it or... do not update the progress bar until 3-4%...

**Comment by JF002** [comment]
Fixed in 0.14 with the integration of LVGL7
