### ISSUE TITLE
Unresponsive touchscreen: no swiping / taping | no heartbeat monitor

### ISSUE THREAD

**Issue by MonsieurPaulLeBoulanger** [JF002/InfiniTime#590]
### Description

I have just received my PineTime yesterday and the touchscreen doesn't respond : I can't swipe (any way) so I'm unable to use the watch.
The step counter works properly but my heartbeat is not detected.
I can sync the watch with my laptop (siglo) and my smartphone (gadgetbridge).

I tried to update the firmware using siglo but I can't validate it as I'm unable to swipe to the firmware screen.
I also tried a hard reset (draining the battery).

### What's expected?
Swiping on the touch screen should show other screens with icons, buttons...
The heartbeat monitor should detect my heartbeat as, afaik, I'm not dead ;)

### Environment
    PineTime sealed
    InfiniTime 1.0.0
    Bootloader 0.14.1
    Recovery 0.14.1

May be the same kind of issue like [https://github.com/JF002/InfiniTime/issues/329](https://github.com/JF002/InfiniTime/issues/329)

**Comment by Riksu9000** [comment]
If the touchscreen never responds, this sounds like a hardware fault. You should probably contact Pine64 to get a replacement.

**Comment by MonsieurPaulLeBoulanger** [comment]
Sure, I was wondering if I could do more tests & checks, just in case.

**Comment by Avamander** [comment]
If it's an unsealed version, just reset the touch panel cable first.

**Comment by Riksu9000** [comment]
You could try flashing this. It tries to read the Chip id, vendor id and firmware version from the touch controller and display it in the digital watch face. I'm assuming you can only see the digital watch face. If this shows ff or freezes, we can be certain that the touch controller isn't working.

![test](https://user-images.githubusercontent.com/37774658/129728478-1f4aa35a-466a-4e5e-adca-237fb0abf8cf.jpg)

[pinetime-mcuboot-app-dfu-1.3.0.zip](https://github.com/JF002/InfiniTime/files/7000019/pinetime-mcuboot-app-dfu-1.3.0.zip)

**Comment by MonsieurPaulLeBoulanger** [comment]
hmm, I guess `0 0 0` isn't really expected.
![index](https://user-images.githubusercontent.com/3874793/129734031-4dc71173-af01-4869-9178-6104db89a4d2.jpg)

**Comment by Riksu9000** [comment]
Interesting. It seems that communication with the chip was successful, but maybe the chip is partially faulty?

**Comment by MonsieurPaulLeBoulanger** [comment]
@Riksu9000 let me know if I can try something else.
And thank you for your help ;)

**Comment by MonsieurPaulLeBoulanger** [comment]
Just received a spare PineTime that works fine.

**Comment by asdfzerozero** [comment]
I seem to be having this issue - I do not use this often but I tried to upgrade to 1.7.1 and I am still frozen.  unsure how to troubleshoot at this point -- wondering what list of tools I can use to debug? (closed pinetime)
