### ISSUE TITLE
Too hard to adjust timer

### ISSUE THREAD

**Issue by hellojaccc** [JF002/InfiniTime#596]
https://user-images.githubusercontent.com/71537512/129831969-958dff50-39ef-4ad7-b246-9eda19813bf8.MOV

Touch is working okay in another apps, but not timer

**Comment by Riksu9000** [comment]
Touch should work the same way in Timer as in all other apps. Touch in general is just sluggish currently and the buttons are small. #554 will make the buttons easier to hit and #492 will improve touch responsiveness.
