### ISSUE TITLE
Music app buttons don't work + swipe issue

### ISSUE THREAD

**Issue by hubmartin** [JF002/InfiniTime#599]
Hi, can anybody try music app with android please? I do not own other phone to test with.

In current develop ee44b6f the buttons don't work. When on debugger then it seems like the events LVGL aren't triggered at all.
When I tried tag 1.3.0 the buttons works reliably.

On top of that, in 1.3.0 and current develop ee44b6f when I do the swipe gesture for previous/next then it skips several songs. I can also see that selected song changes quickly few times. So it seems like it is sending multiple commands on single swipe, is this possible? (I do not have random song. When in 1.3.0 click previous/next button it skips correctly one song, when I do swipe then it skipps few of them). (it also seems that in ee44b6f the swipe sometimes restarts watches)

Videos:
https://youtu.be/OYB3acYyOZ8 1.3.0 - buttons work properly, single swipe skips multiple songs
https://youtu.be/yw1J42DHpdY - develop branch ee44b6f, buttons do not work, swipe skips multiple songs, sometimes freezes watches

In both videos I use same gadgetbridge. I also changed FW few times to develop and 1.3.0 to confirm that for example music app or android doesn't have its issues.

**Comment by Riksu9000** [comment]
I found the cause of button presses getting ignored and fixed it in #600.

At least in Twos a single swipe has always been able to activate a couple of times. Recently it has gotten  worse somehow, but #492 should fix it.

**Comment by hubmartin** [comment]
Awesome! Thanks for quick fix and merge.
