### ISSUE TITLE
Build firmware Github action fails with errors.

### ISSUE THREAD

**Issue by Anomalocaridid** [JF002/InfiniTime#603]
The automatic build action seems to consistently fail with the following errors:

> Unable to process command '::add-path::/home/runner/work/_temp/arm-none-eabi/bin' successfully.

> The `add-path` command is disabled. Please upgrade to using Environment Files or opt into unsecure command execution by setting the `ACTIONS_ALLOW_UNSECURE_COMMANDS` environment variable to `true`. For more information see: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/

**Comment by Avamander** [comment]
Fixed by https://github.com/JF002/InfiniTime/pull/579
