### ISSUE TITLE
Rapid battery drain after 35%

### ISSUE THREAD

**Issue by joseph58tech** [JF002/InfiniTime#609]
I've noticed that after my watch battery hits 35%, it drain obnoxiously quick 
![Screenshot_20210828-020547](https://user-images.githubusercontent.com/82465749/131209823-38353743-5a21-4446-b7bf-e077ca001ced.png)

**Comment by joseph58tech** [comment]
Alright, it was the low charge during upgrade

**Comment by JF002** [comment]
Yes, this is a known behavior. It's caused by the non-linear discharge curve of the battery.
Battery level measurement will be improved in InfiniTime 1.4 :)

**Comment by joseph58tech** [comment]
Alright thanks

**Comment by JF002** [comment]
InfiniTime 1.4 is released, it should improve the battery level measurement. Feel free to provide some feedbacks when you try it!

**Comment by joseph58tech** [comment]
I just download it, I will install in a little bit, but anyways thanks for understanding

**Comment by joseph58tech** [comment]
Just installed infiniTime 1.4 and it is working flawlessly

**Comment by pag-r** [comment]
Updated to 1.4, Battery level = 37 - everything fine. Day after - battery drained completely. Seems like to doesn't fully works
