### ISSUE TITLE
[Feature request] Vibrate on lost connection

### ISSUE THREAD

**Issue by adocampo** [JF002/InfiniTime#670]
I've found myself missing a lot of notifications because PT has disconnected from gadgetbridge. I don't know why it could be, but PT disconnects silently.
I'm missing a pebble function, and I think it could be of use in this scenario. When pebble got disconnected for any reason, it vibrated and the watchface changed during a few seconds (10'' or the like) with the message "Where is my phone". 
I think this  could help users to make them re-connect as soon as possible.

**Comment by Riksu9000** [comment]
Duplicate of #597
