### ISSUE TITLE
Call notification stuck - v1.4.0

### ISSUE THREAD

**Issue by arvchristos** [JF002/InfiniTime#676]
Hello,
I've been using v1.4.0 and I encountered the following issue:

Whenever I get a call and I answer it from my mobile device and not the call notification, the pinetime continues vibrating indefinitely. I think this must be a bug because the call is already answered. 

Thank you!

**Comment by Avamander** [comment]
Duplicate of https://github.com/JF002/InfiniTime/issues/591
