### ISSUE TITLE
Cannot download the 1.4 .zip file (Github reports: SignatureDoesNotMatch)

### ISSUE THREAD

**Issue by bhibb** [JF002/InfiniTime#683]
When trying to download the latest release of the Infinitime 1.4, when I select the link for the .zip file, I receive the following error from Github. Does it need to be re-uploaded?
![image](https://user-images.githubusercontent.com/33728168/134077520-da489ce1-bbfb-4342-9d30-9b38d1c83c31.png)
![infinitime](https://user-images.githubusercontent.com/33728168/134077730-3ff0220f-84ab-403d-883e-f96f99a0711b.jpg)

**Comment by Avamander** [comment]
Probably a GitHub bug, try again later.

**Comment by bhibb** [comment]
I hope so. It seems to be a broken link and companion apps like Siglo which fetch it are also broken. :*(

**Comment by bradman117** [comment]
Thats odd. I am experiencing same issue. v1.3 download still works.

**Comment by bhibb** [comment]
In the meantime until it's fixed, maybe someone who's already downloaded it can host it?

**Comment by bradman117** [comment]
bump

**Comment by bhibb** [comment]
The error appears to be the following:

```
SignatureDoesNotMatch
The request signature we calculated does not match the signature you provided. Check your key and signing method.
```
Looks like maybe something was off with the uploaded signature.

**Comment by BCNelson** [comment]
It is working for me now.

**Comment by bhibb** [comment]
Confirmed. It's working now! I'm closing this issue!
