### ISSUE TITLE
Lift to Wake Sensitivity Control

### ISSUE THREAD

**Issue by Batcastle** [JF002/InfiniTime#695]
With my Pinetime, it seems Infinitime is a little overzealous with Lift-to-wake for me. 

I notice my watch waking up while I am  driving, typing, or even other daily tasks. While not necessarily always a bad thing, it can be distracting (eg. Driving).

I was wondering if it would be possible to add a Lift-To-Wake sensitivity setting of some sort so that people like myself can turn the sensitivity down and keep from being distracted and potentially save a little bit of battery life.

Thanks!

**Comment by Riksu9000** [comment]
Duplicate of #548

**Comment by Batcastle** [comment]
@Riksu9000 yep you're right. I didn't see it when making sure that there weren't any duplicates. I'll close this issue.
