### ISSUE TITLE
flash of old/previous time when using PineTimeStyle watchface

### ISSUE THREAD

**Issue by m4lvin** [JF002/InfiniTime#704]
When turning on the watch using the PineTimeStyle watchface, the old (previously shown) time is shown for a very short moment before the current time is shown. I tried to film it:

![pinetimestyle-previous-time-flash](https://user-images.githubusercontent.com/2990728/135455909-79c46e26-902a-447b-af2e-b8d4b9195f83.gif)

This is with version 1.6.0, but already was happening before.

**Comment by escoand** [comment]
Duplicate of #72

**Comment by m4lvin** [comment]
Thanks, and sorry for not managing to find that other issue!
