### ISSUE TITLE
Potential Bluetooth failure after a failed DFU

### ISSUE THREAD

**Issue by Avamander** [JF002/InfiniTime#76]
I think I just stumbled upon a state where a DFU update fails, it returns to the main screen, but I couldn't establish a Bluetooth connection any more. Rebooting the watch fixed it. 

This needs investigation because it's very bad with sealed PineTimes

**Comment by Avamander** [comment]
Just managed to make it happen again, so I'm pretty sure it's an issue.

**Comment by davorvr** [comment]
I can confirm this with 0.10.0, failed DFU update makes the watch unreachable unless I reboot it.

**Comment by drpong2** [comment]
I've also encountered this issue on 0.9.0, but don't recall having the issue on 0.10.0 or with the RC3 bootloader.

I can do further testing and confirm.

**Comment by Avamander** [comment]
https://github.com/JF002/Pinetime/releases/tag/0.13.0 was released, we'll have to see if that fixed it.

**Comment by petterhs** [comment]
> https://github.com/JF002/Pinetime/releases/tag/0.13.0 was released, we'll have to see if that fixed it.

I have not had this issue since 0.13.0. Could be because OTA failures are rare now, but I think it is fixed

**Comment by MysteriousLog6** [comment]
Prithee closeth this issue

**Comment by JF002** [comment]
With pleasure :)
