### ISSUE TITLE
Screen update bugged after certain hardware scrolling stuff has happened

### ISSUE THREAD

**Issue by TT-392** [JF002/InfiniTime#91]
his was an issue I noticed when I was testing Electr0Lyte's pong code. If you start the watch, go to the validation screen, and scroll down. Then on (I am guessing 80 horizontal lines) the screen isn't updating correctly and causing weird stripes to form on the screen when the ball crosses.

I am guessing this is related to the screen being left in a scrolled state after having left this version validation screen, and this is somehow not correctly handled when writing stuff to the screen.

I noticed this with pong, but I am pretty sure that other weird graphical bugs on other apps where stuff is moving are related
![yHxwTkmTROdLaWrgYcBJkccP](https://user-images.githubusercontent.com/36132003/95615003-c9e3f080-0a67-11eb-894f-4a682c1da4ca.jpg)

**Comment by Avamander** [comment]
Can confirm the same happens when mid-scroll a DFU update starts, a full display scroll might need a lock or the display some kind of transaction buffer.

**Comment by JF002** [comment]
Fixed in 0.15
