### ISSUE TITLE
Music: long titles move back and forth too fast

### ISSUE THREAD

**Issue by arteeh** [JF002/InfiniTime#97]
0.8.2

When playing a song with a title that's longer that the Pinetime screen can draw (about 18 or 19 characters?), the title moves back and forth extremely fast, making it nearly unreadable. 

Expected: The title moves back and forth slowly, so it's easy to read.

Ideal: The title moves forward, then when it's at the end, it immediately goes back to the front. (People don't read backwards so text moving backwards is unintuitive)

**Comment by arteeh** [comment]
This may be fixed with #96

**Comment by Avamander** [comment]
It is not fixed in the PR, it's something in LVGL. That's a topic for an another PR.

**Comment by jedmijares** [comment]
I took a shot at adjusting this in #152, here's a video showing what it looks like: https://www.youtube.com/watch?v=PvBWN1-NBNU
